name: Resource Deletion Check

on:
  schedule:
    - cron: "0 0 * * *" # Run at midnight UTC daily
  workflow_dispatch: # Allow manual triggers

jobs:
  check-source:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      # Compile TypeScript (assuming your TS config outputs to dist/)
      - name: Build TypeScript
        run: yarn build

      # Run your TypeScript script (compiled JavaScript)
      - name: Run resource deletion check
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: node dist/run.js --resource-deletion-check
