name: Daily TypeScript Script

on:
  schedule:
    # Runs at 03:00 UTC every day
    - cron: "0 3 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # Install dependencies
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      # Compile TypeScript (assuming your TS config outputs to dist/)
      - name: Build TypeScript
        run: yarn build

      # Run your TypeScript script (compiled JavaScript)
      - name: Execute Script
        run: node dist/run.js
