name: Vivaldi Source Publication Check

on:
  schedule:
    # Runs at 03:00 UTC every day
    - cron: "0 3 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # Enable Corepack and Yarn-berry
      - name: Enable Corepack
        run: corepack enable

      # Install dependencies
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      # Compile TypeScript (assuming your TS config outputs to dist/)
      - name: Build TypeScript
        run: yarn build

      # Run your TypeScript script (compiled JavaScript)
      - name: Run source check
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
          DO_SSH_KEY_ID: ${{ secrets.DO_SSH_KEY_ID }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: node dist/sourcePublicationCheck.js
