name: Vivaldi Source Publication Check

on:
  schedule:
    # Runs at 01:00 UTC (03:00 Paris time) every day
    - cron: "0 1 * * *"
  workflow_dispatch: # Allow manual triggers

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: myEnvironement

    steps:
      # Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # Enable Corepack and Yarn-berry
      - name: Enable Corepack
        run: corepack enable

      # Install dependencies
      - name: Install dependencies
        run: yarn install --immutable

      # Compile TypeScript (assuming your TS config outputs to dist/)
      - name: Build TypeScript
        run: yarn build

      # Run your TypeScript script (compiled JavaScript)
      - name: Run source publication check
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
          DO_SSH_KEY_ID: ${{ vars.DO_SSH_KEY_ID }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SMTP_SERVER: ${{ vars.SMTP_SERVER }}
          SMTP_PORT: ${{ vars.SMTP_PORT }}
          SMTP_USERNAME: ${{ vars.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_USER_EMAIL: ${{ vars.GIT_USER_EMAIL }}
        run: node dist/sourcePublicationCheck.js
